### ISSUE TITLE
Residues on the protein alphabet website do not bond to left or right

### ISSUE THREAD

**Issue by paulflang** [KarrLab/bpforms#110]
The residues on the protein alphabet website do not bond to left or right. Not sure if this is intended. The YAML file shows left- and right-bond atoms.

**Comment by jonrkarr** [comment]
I see left and right bonding sites colored blue and green. What specifically are you referring to?

**Comment by paulflang** [comment]
`Binds left?` and `Binds right?`
![image](https://user-images.githubusercontent.com/47160416/95134946-fc3dd700-0763-11eb-9051-973edba8faf0.png)

**Comment by jonrkarr** [comment]
Basically, the two colors mean there are two binding sites. One color means one binding site (i.e. an N or C cap). Zero colors means no binding sites (this would be a fairly uninteresting case).

**Comment by paulflang** [comment]
But why do `Binds left?` and `Binds right?` both say `No`?

**Comment by jonrkarr** [comment]
Looks like the JS script was never updated when the properties were renamed. I fixed this.
