### ISSUE TITLE
Can `bpforms` visualize the svg strings from biopolymers?

### ISSUE THREAD

**Issue by paulflang** [KarrLab/bpforms#111]
I do not find an example for visualization in the docs or Jupyter notebook, so I've been doing
```Python
from IPython.display import SVG, display
dna_form = bpforms.DnaForm().from_str('ACGT')
image = dna_form.get_image()
display(SVG(image))
```
in the notebook or just saved the SVG string to a file and viewed it in  my browser. Is there a better way of doing this?

**Comment by jonrkarr** [comment]
SVG is one of the most common formats for images. SVG files can be viewed by all modern web browsers.

1. Save SVG to file.
2. Open file in web browser.

SVG images can also be viewed inside Jupyter notebooks as Paul illustrated above.
