### ISSUE TITLE
Reach out to potential users

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/bpforms#38]
- Topdown proteomics -- ProteoForm nomenclature
   - Richard LeDuc: Richard.leduc@northwestern.edu
   - Veit Schwammle: veits@bmb.sdu.dk
   - Michael Shortreed: mshort@chem.wisc.edu
   - Stefan Solntsev: solntsev@wisc.edu
- Maintainers of DNAmod, MODOMICS, RESID, etc.
  - DNAmod: Michael Hoffman: michael.hoffman@utoronto.ca
  - MODOMICS
    - Janusz Bujnicki: iamb@genesilico.pl
    - Henri Grosjean: henri.grosjean@cgm.cnrs-gif.fr
    - Magdalena Machnicka: mmika@genesilico.pl
    - Kaja Milanowska: kaja@genesilico.pl
    - Pietro Boccaletto: pietro.boccaletto@gmail.com
  - RESID: John Garavelli: jsgarave@udel.edu
  - MethDB: Christoph Grunau: christoph.grunau@univ-perp.fr
  - MethSMRT: Zhi Xie: xiezhi@gmail.com
  - RMBase: Jian-Hua Yang: yangjh7@mail.sysu.edu.cn
  - RNA Modification DB
    - Paul Agris: pagris@albany.edu
    - Daniele Fabris: fabris@albany.edu
    - Srivathsan V. Ranganathan: svranganathan@albany.edu
  - PSI-MOD:
    - Pierre-Alain Binz, pierre-alain.binz@chuv.ch
    - Sylvie Ricard-Blum, sylvie.ricard-blum@univ-lyon1.fr
  - dbPTM: 
    - Tzong-Yi Lee: francis@saturn.yzu.edu.tw
    -  Hsien-Da Huang: huanghsienda@cuhk.edu.cn
  - PIR
     - Cathy Wu: wuc@dbi.udel.edu
     - Darren Natale: dan5@georgetown.edu
     - Cecilia Arighi: arighi@dbi.udel.edu
     - Judith Blake: Judith.blake@jax.org
   - UniMod: John Cottrell: jcottrell@matrixscience.com
- Maintainers of SBOL (expanded amino acid code)
  - Herbert Sauro: hsauro@uw.edu
  - Chris Meyers: myers@ece.utah.edu
  - Curtis Madsen: ckmadsen@bu.edu
  - Nicholas Roehner: nicholasroehner@gmail.com
- Epigenetics: ask Gang Fang for advice
- Synthetic genetic code: ask Stephen Fried for advice

**Comment by jonrkarr** [comment]
Hi `XXX`,

I'm reaching out to share _BpForms_ (https://www.bpforms.org), a new toolkit for concretely describing and calculating properties of modified DNA, RNA, and protein, which I think would be helpful to your research on `XXX`. By unambiguously communicating the structures of modified DNA, RNA, and proteins, _BpForms_ aims to help researchers integrate data and model epigenetic, post-transcriptional and post-translational modification.

We developed _BpForms_ to help us describe the DNA, RNA, and proteins represented by our whole-cell models (see https://wholecell.org for more information). We think that _BpForms_ would also be a valuable tool for your efforts to `XXX`.

The _BpForms_ toolkit includes four components:
- A simple FASTA-like notation for describing the primary structures of modified DNA; RNA, and proteins, including any uncertainty in their structures;
- Three alphabets of hundreds of non-canonical nucleic and amino acids curated from DNAmod, MODOMICS, and RESID, as well as the ability to extend these alphabets and/or create additional alphabets;
- Web, command line, and Python tools for calculating properties of modified DNA, RNA, and proteins such as their major protonation state, formula, molecular weight, and charge; and
- A brief tutorial and detailed documentation.

_BpForms_ is available open-source under the MIT License.

We hope _BpForms_ is helpful to your work. Please reach out for any help using _BpForms_.

Regards,
Jonathan Karr
Yassmine Chebaro
Paul Lang

**Comment by ychebaro** [comment]
What do you think of : 
Huillin Li, mass spectrometry scientist, (https://www.nature.com/articles/nchem.2908), we shared the same office when she was in Strasbourg and I think this could interest her.
She is currently a professor in the School of Pharmaceutical Sciences, Sun Yat-sen University.

**Comment by jonrkarr** [comment]
Sure. This isn't an exhaustive list. Feel free to add more.

We can use the template message about and mail merge. Feel free to add more people to this table:
https://docs.google.com/spreadsheets/d/1_iRIrXvbOFnIGgyUI4s5p1wW_cxcr7bCzqgujEh9SQE/edit?usp=sharing

**Comment by jonrkarr** [comment]
Done
