### ISSUE TITLE
bpforms as command line: problem with validate and user-defined expression

### ISSUE THREAD

**Issue by ychebaro** [KarrLab/bpforms#45]
When using bpforms as command line interface, there seems to be a need for single quotes around a user-defined bpform:

bpforms validate dna A[id: "m2C"]
bpforms: error: unrecognized arguments: m2C]

bpforms validate dna 'A[id: "m2C"]'
Form is valid

**Comment by jonrkarr** [comment]
This is generally true for command line programs. Spaces and other non-alphanumeric characters delineate separate arguments. Quotation marks are generally used to encapsulate arguments.
